using UnityEngine;

public class DialogueTrigger : MonoBehaviour
{
    public DialogueManage dialogueManager;   // à¹ƒà¸Šà¹‰à¸Šà¸·à¹ˆà¸­ DialogueManage
    [TextArea]
    public string[] sentences;

    private bool triggered = false;

    void OnTriggerEnter2D(Collider2D other)
    {
        if (triggered) return;

        if (other.CompareTag("Player"))
        {
            triggered = true;

            PlayerMovement pm = other.GetComponent<PlayerMovement>();
            pm.SetCanMove(false); // ðŸ”’ à¸«à¸¢à¸¸à¸”à¸œà¸¹à¹‰à¹€à¸¥à¹ˆà¸™à¹€à¸”à¸´à¸™

            PlayerShoot ps = other.GetComponent<PlayerShoot>();
            if (ps != null)
                ps.canShoot = false; // ðŸ”’ à¸«à¸¢à¸¸à¸”à¸¢à¸´à¸‡

            dialogueManager.StartDialogue(sentences, pm);
        }
    }
}
